# Generated by Django 3.2.9 on 2021-12-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=29)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(default='empty', max_length=100)),
                ('name', models.CharField(default='empty', max_length=100)),
                ('lastname', models.CharField(default='empty', max_length=100)),
                ('country', models.CharField(default='empty', max_length=25)),
                ('dateOfBirth', models.DateField(default='empty')),
                ('address', models.TextField(default='empty', max_length=254)),
            ],
        ),
    ]
