# Generated by Django 3.2.9 on 2021-12-20 00:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0001_initial'),
        ('seller', '0002_auto_20211216_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=100)),
                ('brandNew', models.BooleanField(default=True)),
                ('inMlStorage', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('imgUrl', models.TextField(default='Empty', max_length=254, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(max_length=30)),
                ('paymentMethod', models.TextField(choices=[('DEBIT CARD', 'Debitcard'), ('OXXO', 'Oxxo'), ('CREDIT CARD', 'Creditcard')], default='DEBIT CARD', max_length=35)),
                ('isDetained', models.BooleanField(default=False)),
                ('isReported', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.buyer')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.purchase')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewDescription', models.TextField(max_length=254)),
                ('calification', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.purchase')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportDescription', models.TextField(max_length=254)),
                ('date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buyer.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.purchase')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.seller')),
            ],
        ),
    ]
