# Generated by Django 3.2.9 on 2021-12-20 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ForeignKey(default=1, max_length=254, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.categorie'),
        ),
    ]
